[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
calls_program = "d67T6FJT4Hnhp8FURL4V71XB9fkSzXmp7wUN4XrCxbC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
